### ISSUE TITLE
在window环境下显示连接成功但是不进入管理界面且tomcat报错ifconfig": CreateProcess error=2, 系统找不到指定的文件

### ISSUE THREAD

**Issue by r1ghrfhd** [feihong-cs/JspMaster#1]

**Comment by feihong-cs** [comment]
tomcat报错是正常的，程序先会连接上shell，执行命令 ipconfig/ifconfig，根据执行结果判断是windows还是linux，所以windows tomcat会报这个错误。“在window环境下显示连接成功但是不进入管理界面”这个能不能贴2张图看一看，从而看能不能判断出问题可能在哪，因为本地测试没有复现这个问题。另外，请提供下选择的 shell 类型以及是否启用了加密，谢谢。

**Comment by r1ghrfhd** [comment]
你好，我的环境是jdk1.8 tomcat 7.0.100 win10
![image](https://user-images.githubusercontent.com/16057303/83323459-78de1780-a291-11ea-89dd-ddde73759982.png)
这里不使用加密的shell，使用最基本的basic.jsp 连接类型basic
显示连接成功然后双击连接失败不进入mainui界面
![image](https://user-images.githubusercontent.com/16057303/83323479-927f5f00-a291-11ea-9361-f98bbb0c1994.png)
通过burp发包可以看到
![image](https://user-images.githubusercontent.com/16057303/83323489-9e6b2100-a291-11ea-9fcd-89b30722afe6.png)
通过wireshark抓包也能看到部分命令得到执行
看了源码时根据ipconfig ifconfig的返回值里面是否包含window linux 来判断时哪种服务器类型
但是这里确实无法成功，也有可能和我环境有关系
然后如果jdk版本1.6的话java.util.base64无法向下兼容 
最后感谢作者开发这个jsp管理工具。

**Comment by feihong-cs** [comment]
谢谢反馈，这个问题我会跟一下。

**Comment by feihong-cs** [comment]
不好意思，前段时间被公司派去忙项目上的事情了，才得空。你方便留个联系方式吗，邮箱啥的都行，我发个测试包给你，看看能不能定位这个问题到底在哪。

**Comment by r1ghrfhd** [comment]
感谢  qq邮箱:3516653160@qq.com

**Comment by feihong-cs** [comment]
问题已解决，将关闭 issue
